SELECT 
    GJE.SubledgerVoucherDataAreaId,
    COUNT(*) AS NumeroTransazioni
FROM 
    GENERALJOURNALENTRY GJE
JOIN 
    GENERALJOURNALACCOUNTENTRY GJAE ON GJE.RECID = GJAE.GeneralJournalEntry
JOIN 
    POSTINGTYPE PT ON PT.Value = GJAE.POSTINGTYPE
JOIN 
    JOURNALCATEGORY JC ON GJE.JOURNALCATEGORY = JC.Value
JOIN 
    DIMENSIONATTRIBUTEVALUECOMBINATION DAVC ON GJAE.LEDGERDIMENSION = DAVC.RECID
JOIN 
    DIMATTRIBUTEGROUPCHARTOFACCOUNTS DAGCA ON DAGCA.VALUE = DAVC.GROUPCHARTOFACCOUNTSVALUE
LEFT JOIN 
    LEDGERJOURNALTRANSACTION LJT ON LJT.GENERALJOURNALENTRY = GJE.RECID
LEFT JOIN 
    LEDGERJOURNALTYPE LJTY ON LJTY.Value = LJT.JOURNALTYPE
JOIN 
    MAPPINGCLOSINGPERIODACTIVITY MCPA ON MCPA.postingtypelabel = pt.label AND mcpa.journalcategorylabel = jc.label
JOIN 
    CLOSINGPERIODACTIVITY CPA ON CPA.Id = MCPA.ActivityId
WHERE  
    GJE.CreatedDateTime >= '2020-01-01'
GROUP BY 
    GJE.SubledgerVoucherDataAreaId
HAVING 
    COUNT(*) < 900000
ORDER BY NumeroTransazioni