WITH RankedRows AS (
    SELECT DISTINCT
        GJAE.RECID as GjaeRecId,
        DAGCA.VALUE as GroupChartOfAccountsValue,
        GJE.PostingLayer,
        GJE.SubledgerVoucherDataAreaId,
        GJE.CreatedBy,
        GJAE.Text,
        CPA.Id,
        ROW_NUMBER() OVER (PARTITION BY CPA.Id ORDER BY GJAE.RECID) AS RowNum
    FROM 
        GENERALJOURNALENTRY GJE
        JOIN GENERALJOURNALACCOUNTENTRY GJAE ON GJE.RECID = GJAE.GeneralJournalEntry
        JOIN POSTINGTYPE PT ON PT.Value = GJAE.POSTINGTYPE
        JOIN JOURNALCATEGORY JC ON GJE.JOURNALCATEGORY = JC.Value
        JOIN DIMENSIONATTRIBUTEVALUECOMBINATION DAVC ON GJAE.LEDGERDIMENSION = DAVC.RECID
        JOIN DIMATTRIBUTEGROUPCHARTOFACCOUNTS DAGCA ON DAGCA.VALUE = DAVC.GROUPCHARTOFACCOUNTSVALUE
        LEFT JOIN LEDGERJOURNALTRANSACTION LJT ON LJT.GENERALJOURNALENTRY = GJE.RECID
        LEFT JOIN LEDGERJOURNALTYPE LJTY ON LJTY.Value = LJT.JOURNALTYPE
        JOIN MAPPINGCLOSINGPERIODACTIVITY MCPA ON MCPA.postingtypelabel = pt.label AND MCPA.journalcategorylabel = jc.label
        JOIN CLOSINGPERIODACTIVITY CPA ON CPA.Id = MCPA.ActivityId
    WHERE  
        GJAE.Text != ''
)
SELECT 
    GjaeRecId,
    GroupChartOfAccountsValue,
    PostingLayer,
    SubledgerVoucherDataAreaId,
    CreatedBy,
    Text,
    Id
FROM RankedRows
WHERE RowNum <= 600000;