SELECT
    PT.Label AS PostingTypeLabel,
    GJAE.PostingType,
    JC.Label AS PossibleJournalCategory
FROM GENERALJOURNALENTRY GJE
JOIN GENERALJOURNALACCOUNTENTRY GJAE ON GJE.RECID = GJAE.GeneralJournalEntry
JOIN POSTINGTYPE PT ON PT.Value = GJAE.POSTINGTYPE
JOIN JOURNALCATEGORY JC ON GJE.JOURNALCATEGORY = JC.Value
GROUP BY PT.Label, GJAE.PostingType, JC.Label
order by GJAE.POSTINGTYPE;
