	SELECT distinct
	GJAE.RECID as GjaeRecId,
	GJE.RECID as GjeRecId,
	GJE.AccountingDate,
	GJE.CreatedDateTime,
	GJAE.LedgerDimension,
	DAGCA.VALUE as GroupChartOfAccountsValue,
	DAGCA.name AS GroupChartOfAccountsName,
    GJE.Ledger,
    GJE.PostingLayer,
    GJE.SubledgerVoucher,
    GJE.SubledgerVoucherDataAreaId,
    GJE.CreatedBy,
    JC.Label AS JournalCategory,
    GJAE.AccountingCurrencyAmount,
    PT.Label AS PostingTypeLabel,
	GJAE.PostingType AS PostingTypeValue,
    GJAE.MainAccount,
    GJAE.Text,
	LJT.JournalType,
	LJTY.Label AS JournalTypeLabel,
	LJT.NumOfLines,
	LJT.JournalTotalDebit,
	LJT.JournalTotalCredit,
	LJT.Count as CountLedgerJournal,
    GJAE.ReportingCurrencyAmount,
    GJAE.TransactionCurrencyAmount,
    GJAE.TransactionCurrencyCode
    --SDH.TypeEnumName
	------------
/*	GJE.RECID,
	GJAE.GeneralJournalEntry,
	GJE.JOURNALCATEGORY,
	JC.Value,
	GJAE.RECID,
	SJAE.GENERALJOURNALACCOUNTENTRY,
	SJAE.SUBLEDGERJOURNALENTRY,
	SJE.RECID,
	SJE.ACCOUNTINGEVENT,
	AE.RECID,
	AE.SOURCEDOCUMENTHEADER,
	SDH.RECID
*/
FROM GENERALJOURNALENTRY GJE
JOIN GENERALJOURNALACCOUNTENTRY GJAE ON GJE.RECID = GJAE.GeneralJournalEntry
JOIN POSTINGTYPE PT ON PT.Value = GJAE.POSTINGTYPE
JOIN JOURNALCATEGORY JC ON GJE.JOURNALCATEGORY = JC.Value
JOIN DIMENSIONATTRIBUTEVALUECOMBINATION DAVC ON GJAE.LEDGERDIMENSION = DAVC.RECID
JOIN DIMATTRIBUTEGROUPCHARTOFACCOUNTS DAGCA ON DAGCA.VALUE = DAVC.GROUPCHARTOFACCOUNTSVALUE
left JOIN LEDGERJOURNALTRANSACTION LJT ON LJT.GENERALJOURNALENTRY = GJE.RECID
left JOIN LEDGERJOURNALTYPE LJTY ON LJTY.Value = LJT.JOURNALTYPE

WHERE GJE.SUBLEDGERVOUCHERDATAAREAID = 'it01'

ORDER BY GJE.ACCOUNTINGDATE